<a href="https://colab.research.google.com/github/K-107/exercise/blob/main/Eig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 고유값분해

https://post.naver.com/viewer/postView.naver?volumeNo=28714805&memberNo=21815

In [37]:
# numpy의 svd 모듈 import
import numpy as np

# [A, B] = [[A&흑, A&백],[B&흑, B&백]] 행렬곱 [흑, 백]
matrix = [[0.05, 0.45],[0.1, 0.4]]
A = np.array(matrix)
A

array([[0.05, 0.45],
       [0.1 , 0.4 ]])

In [38]:
eigenvalue, eigenvector = np.linalg.eig(matrix)
eigenvalue, eigenvector

(array([-0.05,  0.5 ]), array([[-0.97618706, -0.70710678],
        [ 0.21693046, -0.70710678]]))

In [39]:
eigenvalue = np.round(eigenvalue, 5) # 소수점 5자리로 반올림
eigenvector = np.round(eigenvector, 5) # 소수점 5자리로 반올림
print("Eigen Value: ")
print(eigenvalue)
print()

Eigen Value: 
[-0.05  0.5 ]



In [40]:
print("Eigen Value Diagonal Matrix \u039B(lambda): ")
eigenvalue = np.array([[eigenvalue[0], 0], [0, eigenvalue[1]]])
print(eigenvalue)
print()

Eigen Value Diagonal Matrix Λ(lambda): 
[[-0.05  0.  ]
 [ 0.    0.5 ]]



In [41]:
print("Eigen Vector Matix P: ")
print(eigenvector)
print()

Eigen Vector Matix P: 
[[-0.97619 -0.70711]
 [ 0.21693 -0.70711]]



In [44]:
print("AP = ")
print(np.round(A@eigenvector, 3))
print()

AP = 
[[ 0.049 -0.354]
 [-0.011 -0.354]]



In [45]:
print("P\u039B =")
print(np.round(eigenvector@eigenvalue, 3))

PΛ =
[[ 0.049 -0.354]
 [-0.011 -0.354]]


In [49]:
print("P\u039BP^-1 =")
print(np.round(eigenvector@eigenvalue@np.linalg.inv(eigenvector),3))
print('A =\n', A)

PΛP^-1 =
[[0.05 0.45]
 [0.1  0.4 ]]
A =
 [[0.05 0.45]
 [0.1  0.4 ]]


In [51]:
print("PP^-1 =")
print(np.round(eigenvector@np.linalg.inv(eigenvector),3))

PP^-1 =
[[ 1. -0.]
 [-0.  1.]]


In [52]:
eigenvalue**10000
# 이건 제곱하면 0으로 수렴한다.

array([[0., 0.],
       [0., 0.]])